 # .gitpod.yml

    # La imagen base que Gitpod usará para tu entorno.
    # 'gitpod/workspace-full-node' ya incluye Node.js, npm, y otras herramientas comunes.
    image: gitpod/workspace-full-node

    # Define las tareas que se ejecutarán en tu espacio de trabajo.
    # Tendremos una tarea para configurar y ejecutar tu backend.
    tasks:
      - name: Setup & Start Backend
        # 'init' se ejecuta una sola vez cuando el espacio de trabajo se inicia por primera vez.
        # Aquí navegamos a la carpeta 'server' y luego instalamos las dependencias de Node.js.
        init: |
          echo "Navegando a la carpeta del servidor..."
          cd server
          echo "Instalando dependencias de Node.js (npm install)..."
          npm install
          echo "Dependencias de Node.js instaladas."

        # 'command' se ejecuta cada vez que el terminal de esta tarea se abre o se reinicia.
        # Aquí iniciamos tu servidor backend usando el script 'dev' de tu package.json.
        command: |
          echo "Navegando a la carpeta del servidor..."
          cd server
          echo "Iniciando servidor Node.js (npm run dev)..."
          npm run dev
          echo "Servidor Node.js iniciado y listo para recibir conexiones."

    # Define los puertos que tu aplicación backend expone.
    # Tu index.js usa el puerto 5000, así que lo configuramos aquí.
    ports:
      - port: 5000 # ¡Este puerto debe coincidir con el PORT en tu index.js!
        onOpen: open-browser # Gitpod abrirá automáticamente una nueva pestaña del navegador en este puerto.
        visibility: public # Hace que el puerto sea accesible desde fuera del espacio de trabajo.

    # Configuración opcional para pre-construcciones (prebuilds).
    # Los prebuilds aceleran el tiempo de inicio de los espacios de trabajo
    # al ejecutar la fase 'init' por adelantado. Muy recomendado.
    github:
      prebuilds:
        main: true # Habilita prebuilds para la rama principal (main/master)
    
